### ISSUE TITLE
Kotlin. Nested configurations do not work in 0.14.4

### ISSUE THREAD

**Issue by ievgen-kapinos** [avast/gradle-docker-compose-plugin#305] opened 2021-07-16 14:04 UTC
Hi there!

Version 0.14.3, works fine. In addition to issue title I have a message when IntelleJ IDE sync Gradle project
```
org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/user_name/Projects/my_project/build.gradle.kts' line: 222
Receiver class com.avast.gradle.dockercompose.ComposeSettings does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
	...
	at Program.execute(Unknown Source)
Caused by: java.lang.AbstractMethodError: Receiver class com.avast.gradle.dockercompose.ComposeSettings does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
	at com.avast.gradle.dockercompose.DockerExecutor.<init>(DockerExecutor.groovy:15)
	...
	at com.avast.gradle.dockercompose.ComposeSettings.<init>(ComposeSettings.groovy:120)
	...
	at com.avast.gradle.dockercompose.ComposeSettings.cloneAsNested(ComposeSettings.groovy:140)
	...
	at com.avast.gradle.dockercompose.ComposeExtension$_getOrCreateNested_closure1.doCall(ComposeExtension.groovy:14)
	...
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	...
	at com.avast.gradle.dockercompose.ComposeExtension.getOrCreateNested(ComposeExtension.groovy:14)
	at com.avast.gradle.dockercompose.ComposeExtension.nested(ComposeExtension.groovy:22)
	at Build_gradle$8.execute(build.gradle.kts:222)
	at Build_gradle$8.execute(build.gradle.kts:3)
	at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
	at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
	at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:194)
	at org.gradle.kotlin.dsl.Accessors8cjdgd6airkzom6u1qviexhyzKt.dockerCompose(Unknown Source)
	at Build_gradle.<init>(build.gradle.kts:221)
	... 151 more

```

Thanks for the great plugin.

**Comment by augi** [comment] 2021-07-17 19:58
Hello, thank you for reporting this issue. I'm looking at [the changes between 0.14.3 and 0.14.4](https://github.com/avast/gradle-docker-compose-plugin/compare/0.14.3...0.14.4), and the only thing that could be related is IMHO upgrade of Gradle from `6.8.3` to `7.1.1`, which includes the update of Groovy from `2.5` to `3.0`.

But as I'm looking that the stacktrace provided, I have no clue what could be the root cause 😢

**Comment by ievgen-kapinos** [comment] 2021-07-18 19:00
Hi @augi 
Good news. With Gradle`7.1.1` all works. Well done!

Bad news. My project is stuck to `6.8.2`, so do many other projects. Of cause, it is up to you support it or not. Reasonable backward compatibility is highly appreciated.

FYI @red-avtovo

**Comment by augi** [comment] 2021-07-18 19:15
I would like to keep support of older Gradle version but I have almost zero knowledge of Kotlin so unfortunately I have no clue where the problem lies 😔 Nay help in this regard is highly welcome, and would be merged & released ASAP.

I think the problem is in Kotlin Gradle/Groovy integration as the error message mentions "receiver" which is Kotlin-specific feature IMHO.

**Closed** 2021-07-19 08:41 UTC
Labels: bug, help wanted

**Comment by ievgen-kapinos** [comment] 2021-07-19 08:59
Hi @augi 

Sorry, cannot contribute now. Anyway, I saw a new release `0.14.5`. I've double checked it. Issue is still the same. 

According to the stack trace it looks we need to implement `getProperty` method in `ComposeSettings`. Probably, this requires to comply with interface `GroovyObject` probably updated in Groovy `3.x` .
