### ISSUE TITLE
Dockerfile with Healthcheck is indefinitely waiting to become healthy not allowing gradle to proceed with other tasks

### ISSUE THREAD

**Issue by smian** [avast/gradle-docker-compose-plugin#194] opened 2019-06-13 18:36 UTC
Hello, great plugin but I have an issue that's keeping me from using it widely. 

In the dockerfile for the backend springboot app, I have a standard healthecheck directive:

`
HEALTHCHECK CMD curl --fail http://localhost:5000/api/actuator/health || exit 1`

When I use ComposeUp, postgres starts up fine and backend starts up fine as far as Springboot startup but the following keeps printing and won't let me run my integration tests:

```
Waiting for backend_1 to become healthy (it's unhealthy)
Waiting for backend_1 to become healthy (it's unhealthy)
...
```

Here's my docker-compose file. If I add `healthcheck: disable: true` then everything seems to be fine but I would like to keep the docker-compose file consistent, instead of having another docker-compose file just for using gradle ComposeUp.

```
version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend-api:latest
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - 5000:5000
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/xolvdb
      - DB_SCHEMA=backend-api
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=a1111111
    volumes:
      - /data/backend-api
#    healthcheck:
#      disable: true 

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a1111111
      - POSTGRES_DB=backenddb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: null
```

Appreciate your help!

**Comment by augi** [comment] 2019-06-14 09:16
Hello, I'm afraid that your issue is not caused by the plugin.

As you can see [here](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L154), the plugin just executes `docker inspect` for the running container and then reads `.State.Health` property.

So could you please try to execute `docker ps` to get ID of the application container, and then `docker inspect CONTAINER_ID`? Then please check what is `State.Health` property of the _inspection json_.

Maybe the healthcheck is failing because `curl` is not installed in your Docker image?

Feel free to reopen this issue if you still believe that your problem is caused by the plugin (e.g. output format of `docker inspect` has been changed).

**Comment by alexromero88** [comment] 2020-01-17 07:33
Hi @augi 

I think @smian is right about the problem, as I'm having the same issue. I think the code is missing something like:
```
if (!"starting".equalsIgnoreCase(healthStatus) && !"unhealthy".equalsIgnoreCase(healthStatus)) {
  logger.lifecycle("${instanceName} health state reported as '$healthStatus' - continuing...")
  break
}
if ("unhealthy".equalsIgnoreCase(healthStatus)) {
  throw new RuntimeException("Container ${containerInfo.containerId} of service ${instanceName} is reported as '${healthStatus}'. Logs:${System.lineSeparator()}${settings.dockerExecutor.getContainerLogs(containerInfo.containerId)}")
}
```

What do you think?

**Comment by augi** [comment] 2020-01-17 10:52
So what you are suggesting is to break the build if a container becomes unhealthy, right? As the health state is initially `starting` and the should become `healthy`, it makes sense. Thanks for your suggestion!

**Comment by alexromero88** [comment] 2020-01-17 17:36
You got it @augi ;) Thanks for reopening the case

**Comment by vierbergenlars** [comment] 2020-01-23 13:01
This would break this plugin for us.
Our applications take about 2 minutes to start up, which is longer than the time that docker takes to report it as unhealthy.

Right now, this is not a problem, because `composeUp` waits until the application becomes healthy (doesn't matter if it is still starting or unhealthy).
But if this was changed, that would break our usage of this plugin.

By the way, if a container fails to become healthy after some period of time (I think 15 minutes) the plugin will composeDown and fail the build already.

**Comment by augi** [comment] 2020-01-23 14:13
Good point, there is `waitForHealthyStateTimeout` configuration option (default is 15 minutes) so it is not true that the plugin waits indefinitely. Isn't this solution for you, @alexromero88?

My expectation was that a unhealthy container cannot become healthy again. But it is not true according to [documentation](https://docs.docker.com/engine/reference/builder/#healthcheck).

@vierbergenlars, maybe consider altering your `--start-period` to a bigger value. Then your container should go from _starting_ directly to _healthy_ state.

**Comment by alexromero88** [comment] 2020-01-23 20:32
Hey @vierbergenlars, as @augi  mentioned, you should tune the `start-period` parameter to fix that problem. 

@augi , about `waitForHealthyStateTimeout`, this is how it is working for me now but it's kind of annoying that if something gets unhealthy in 1 minute, we have to wait 15 mins to stop the gradle task. I'm assuming that an `unhealthy` container is not gonna get healthy just with more time. I still feel the fix I proposed is valid

**Comment by augi** [comment] 2020-01-24 13:38
Hello, I closed this ticket because I would like to keep this plugin as generic as possible, and so I don't want to make this _false_ assumption (that unhealthy container cannot become healthy).

You can still tune the `waitForHealthyStateTimeout` to a lower value (I will add it to the README).

**Closed by augi** 2020-01-24 13:38 UTC
Labels: question
